#!/usr/bin/python3
# ******************************************************************************
# Copyright (c) Huawei Technologies Co., Ltd. 2021-2023. All rights reserved.
# licensed under the Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#     http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN 'AS IS' BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
# PURPOSE.
# See the Mulan PSL v2 for more details.
# ******************************************************************************/

SUCCEED = "Succeed"
PARTIAL_SUCCEED = "Partial.Succeed"
SERVER_ERROR = "Server.Error"
PARAM_ERROR = "Param.Error"
HTTP_CONNECT_ERROR = "Http.Connect.Error"
UNKNOWN_ERROR = "Unknown.Error"
SERVICE_NOT_EXIST = "Service.Not.Exist"
WRONG_FILE_FORMAT = "Wrong.File.Format"
REPO_CONTENT_INCORRECT = "Repo.Content.Incorrect"
REPO_NOT_SET = "Repo.Not.Set"
DATABASE_CONNECT_ERROR = "Database.Connect.Error"
DATABASE_INSERT_ERROR = "Database.Insert.Error"
DATABASE_DELETE_ERROR = "Database.Delete.Error"
DATABASE_QUERY_ERROR = "Database.Query.Error"
DATA_EXIST = "Data.Exist"
DATA_DEPENDENCY_ERROR = "Data.Dependency.Error"
DATABASE_UPDATE_ERROR = "Database.Update.Error"
NO_DATA = "No.Data"
WRONG_DATA = "Wrong.Data"
REPEAT_DATA = "Repeat.Data"
LOGIN_ERROR = "Login.Error"
LOGOUT_ERROR = "Logout.Error"
TOKEN_ERROR = "Token.Error"
REPEAT_LOGIN = "Repeat.Login"
KEY_ERROR = "Key.Error"
CHANGE_PASSWORD = "Change.Password"
REPEAT_PASSWORD = "Repeat.Password"
CHANGE_PASSWORD_FAIL = "Change.Password.Fail"
TOKEN_EXPIRE = "Token.Expire"
TASK_EXECUTION_FAIL = "Task.Execution.Fail"
REPEAT_TASK_EXECUTION = "Repeat.Task.Execution"
SET_AGENT_PLUGIN_STATUS_FAILED = "Set.Agent.Plugin.Status.Failed"
WORKFLOW_ASSIGN_MODEL_FAIL = "Workflow.Assign.Model.Fail"
AUTH_ERROR = "Auth.Error"
AUTH_USERINFO_SYNC_ERROR = "Auth.Userinfo.Sync.Error"
NO_BOUND = "No.Bound"
GENERATION_TOKEN_ERROR = "Generation.Token.Error"
REPEAT_BIND = "Repeat.Bind"
EXECUTE_COMMAND_ERROR = "Execute.Command.Error"
SSH_AUTHENTICATION_ERROR = "Ssh.Authentication.Error"
SSH_CONNECTION_ERROR = "Ssh.Connection.Error"
ADD_HOST_FAILED = "Add.Host.Failed"
PERMESSION_ERROR = "Permission.Error"
SYNCHRONIZE_ERROR = "LocalCluster.Nonsupport.Synchronize"
CACHE_USERINFO_FAILED = "Cache.Userinfo.Failed"
REDIS_CACHEINFO_ERROR = "Redis.Cacheinfo.Error"
CLUSTER_MANAGE_ERROR = "LocalCluster.Nonsupport.Manage.OtherCluster"
CLUSTER_REPEAT_BIND_ERROR = "Cluster.Repeat.Bind.Error"
IP_PING_FAILED = "Ip.Ping.Failed"
TARGET_CLUSTER_MANAGE_ERROR = "TargetCluster.Nonsupport.Be.Managed"
TARGET_CLUSTER_DELETE_ERROR = "TargetCluster.Nonsupport.Be.Deleted"
REDIS_SYNCHRONIZE_TASK_FAILED = "Redis.SynchronizeTask.Failed"
GET_USERINFO_FAILED = "Get.Userinfo.Failed"
PASSWORD_ERROR = "Password.Error"
USER_ERROR = "User.Error"
NO_MANAGED_DATA = "LocalCluster.No.Managed.Data"
TASK_START_FAILED = "Task.Start.Failed"
TASK_RESULT_NOT_FOUND = "Task.No.Result.File"
TASK_RETRY_RUNNING_TASK_ERROR = "Task.Retry.Running.Task.Error"
TASK_CANCEL_NOT_RUNNING_TASK_ERROR = "Task.Cancel.Not.Running.Task.Error"
TASK_DEPENDENCY_ERROR = "Task.Dependency.Error"
OPERATION_WRONG_SUPPORT_CONFIG = "Operation.Wrong.Support.Config"