infrastructure:
  mysql:
    host: "127.0.0.1"
    port: 3306
    username: root
    pool_size: 100
    pool_recycle: 7200
    database: aops
    username: root
  redis:
    host: "127.0.0.1"
    port: 6379
  elasticsearch:
    host: "127.0.0.1"
    port: 9200
    max_es_query_num: 10000000
  prometheus:
    host: "127.0.0.1"
    port: 9090
  zookeeper:
    host: "127.0.0.1"
    port: 2181
  individuation:
    gitee_client_id: 7420ebbb10f7f196de479bd3fe30f120691321143fdae882bc8b3320b3dbb71c
    gitee_client_secret: c6466348389db3a2da3a86ec3b544c19c15f50de513da4dc3edbadaa2e5df792
    redirect_url: http://127.0.0.1:8000/user/account
    exempt_authentication: ?Ohdc,&S*2O].f%-Y1Z~f%~9^U5uD]AQ
    private_key: sfwsfs{)sdf_+$%{$^%$NI07&*()@$&^*(*(^&%(

include: "/etc/aops/conf.d"
domain: "127.0.0.1"

services:
  log:
    log_level: "INFO"
    log_dir: "/var/log/aops"
    max_bytes: 31457280
    backup_count: 40

  email:
    server: smtp.163.com
    port: 25
    sender: xxx@163.com
    authorization_code: xxx
    smtp_ssl: false
    enabled: false